universe                = vanilla
executable              = condor/run_job.sh
arguments               = $(arguments)
MY.SendCredential       = True
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = train_resnet_image_classifier.py, track_point_transformer.py, train_point_transformer_track_classifier.py, train_fusion_ensemble.py, build_event_level_weights.py
output = condor/logs/canary/canary.$(Cluster).$(Process).out
error  = condor/logs/canary/canary.$(Cluster).$(Process).err
log    = condor/logs/canary/canary.$(Cluster).$(Process).log
request_cpus   = 2
request_memory = 8 GB
request_disk   = 8 GB
request_gpus   = 1
require_gpus   = (Capability >= 7.5)
max_retries    = 3
+JobFlavour = "tomorrow"

queue arguments from condor/canary.txt
