universe                = vanilla
executable              = condor/run_gunheavy_compact.sh
arguments               = $(arguments)
MY.SendCredential       = True
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = build_compact_dataset_gun.py, build_compact_dataset.py, build_pgun_compact.py, build_event_level_weights.py, train_resnet_image_classifier.py, pipeline
transfer_output_files   = ""
output = condor/logs/gunheavy_compact/c.$(Cluster).$(Process).out
error  = condor/logs/gunheavy_compact/c.$(Cluster).$(Process).err
log    = condor/logs/gunheavy_compact/c.$(Cluster).$(Process).log
request_cpus   = 8
request_memory = 24 GB
request_disk   = 80 GB
max_retries    = 3
+JobFlavour = "nextweek"

queue arguments from condor/gunheavy_compact.txt
