universe                = vanilla
executable              = condor/run_gunheavy_weights.sh
arguments               = $(arguments)
MY.SendCredential       = True
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = build_category_weights_gun.py, build_event_level_weights.py
transfer_output_files   = ""
output = condor/logs/gunheavy_weights/w.$(Cluster).$(Process).out
error  = condor/logs/gunheavy_weights/w.$(Cluster).$(Process).err
log    = condor/logs/gunheavy_weights/w.$(Cluster).$(Process).log
request_cpus   = 16
request_memory = 32 GB
request_disk   = 20 GB
max_retries    = 3
+JobFlavour = "nextweek"

queue arguments from condor/gunheavy_weights.txt
